name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and run tests for all services
        run: |
          for dir in analytic-service email-service kafka order-service payment-service; do
            echo "Running npm install and test in $dir"
            cd $dir
            npm install
            npm test
            cd ..
          done